### ISSUE TITLE
Load script data from database

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#10]
Currently the script data is stored in an hashmap that is created on startup by parsing json files. This takes ~1minute on my machine. 

Solution: Store the data in the apache database and retrieve it from there

1. Create database tables for the script data and DTO for it.  Maybe, 4 columns are already sufficient: `id BIGINT PRIMARY KEY` `text_type (VARCHAR)`, `documentID (long)` and `json_data`. I think storing the complete json for each document id in each core is sufficient (so, primary key is documentId and textType). The json must not be transformed into a relational schema, but can be just parsed by the JSON parser if it is needed. 
`id` should be different from `documentId` because the documentId sometimes is built by some semantic (like `chapterid`+`00`+`verseId`). This is bad for retrieving the verses ordered or to get the 5 verses before a specific verses. `id` can just be auto-genereted by the database.
2. Add option for parsing the json files and fill the database table (similar to the `enableIndexing` option)
3. Use the DTO in the LookupService / ScriptDataManager. Load the data from the database if it is needed and maybe cache it in an internal hashmap afterwards (so that, if needed again, it can be retrieved from there instead of from the database)

**Comment by dhelmr** [comment]
In `ScriptDataManager`:

* remove the hashMaps `*dataMap`
* in getSurrounding() replace them with a call to the database

**Comment by yum-yab** [comment]
Started a little bit, but encountered a few Problems. But the report of the Project is due, and i need to start working on that. Maybe later.

**Comment by yum-yab** [comment]
Closed because unnecessary
