### ISSUE TITLE
Spell-checking / "Did you mean XXX"

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#12]
Add a "Did you mean XXX" link if the user spelled something wrong. This should especially support book names because the query regex only works if the book names are spelled correctly

**Comment by procrastimax** [comment]
Closed with commit: a0d31a360819bc1b53607305bf62f52c2967ac41

This could definitely be better. But however in cases of wrong written words it works well. Also some times (at low result queries) it suggests "better" queries to improve the number of results.
