### ISSUE TITLE
Export feedback database as JSON 

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#13]
Apparently, a requirement is to export the data of the feedback database as JSON. At least that was said at today's presentation. We should provide a button in the `/logs` endpoint for doing that. 

The report could also include measurements like the [Discounted Cumulative Gain](https://en.wikipedia.org/wiki/Discounted_cumulative_gain), so that it is easy to compare between the evaluation rounds.

**Comment by dhelmr** [comment]
Draft for the export format:
```
{
    "dateStart": "2019-12-12T09:12", //date when the evaluation began
    "dateEnd": "2019-12-13T10:23", //date when the evaluation ended
    "map": "0.54", //Mean Average Precision
    "ndcg": "0.6", //Mean Normalized Discounted Cumulative Gain (over the all topics and the 3 resultlists per topic)
    "topics": [
        {
            "name" : "Murder",
            "query": "murder",
            "description": "Give verses about murder",
            "narrative": "More detailed explanation", 
            "results": {
                "bible": [
                    { //rank #1
                        "id": "324324324", //solr document id
                        "relevant": true
                    },
                    { //rank #2
                        "id": "321123124", //solr document id
                        "relevant": false
                    },
                    // other retrieved results
                ],
                "tanakh" : [], //empty result list means that this core was not enabled for the search
                "koran": [
                    {
                        //...  
                    }
                ]
            },
            "ndcg" : { //ndcg per result list
                "bible": 0.234,
                "koran": 0.123,
                "tanakh": 0
            },
            "ap": { //Average precision per result list
                "bible": 0.234,
                "koran": 0.123,
                "tanakh": 0
            }
        },
        // other topics
    ]
    
}
```

**Comment by dhelmr** [comment]
A "problem" is that we have actually 3 result sets per topic, so we have to compute more than one Average Precision value and/or NDCG per topic. I think we can just build the average over all these values at the end to compute the Mean NDCG.

**Comment by procrastimax** [comment]
Do we always have 3 results per topic? I thought most topics are scripture specific? (Or at least 30 topics are).

And also how do one retrieves the topic list for exporting? In the program there is currently no way to specify this.

**Comment by dhelmr** [comment]
> Do we always have 3 results per topic? I thought most topics are scripture specific? (Or at least 30 topics are).

In that case the Measurements are just 0 and the result array are empty (see tanakh in the example)

> And also how do one retrieves the topic list for exporting? In the program there is currently no way to specify this.

A) Store them in a new table in the database (topics can be matched by the query)
B) Only export the queries and afterwards manually edit the report and insert topic specific fields like `description` and `narrative` by hand.

**Comment by procrastimax** [comment]
yeah, I agree. A seems like a good option, especially if we could easily add/remove topics in a UI which is handled by a DB where we later could join the topic DB with the evaluation DB
Want to create a new issue and assign yourself? @dhelmr  ;)

**Comment by procrastimax** [comment]
Closed with commit: https://github.com/dhelmr/the-holy-search/commit/b290557f6a2eb1cae8e6fb6d141aef44fe9eb456
