### ISSUE TITLE
Setup for evaluation / relevance feedback

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#16]
The question remains how we can do the evaluation in a centralized way, i.e. how can we combine the relevance feedback that each one does on his own machine?

A) Central spring (or database) instance

That would mean we need a central server where everybody can connect to, to do the relevance feedback. It seems like it is not possible to get such a server from university (only a machine which would be exposed as a server). So we would need to host it by ourselves.

B) Evaluate locally and afterwards merge the relevance feedback 

Divide the topics that are to be evaluated and give each person a set of topics. After each one evaluates his set of topics, the results are merged and the relevance metrics can be computed for all 50 topics.

Merging the relevance feedback results could be done in an own git repo maybe.

**Comment by dhelmr** [comment]
Maybe we can use a service like http://pagekite.net/ or https://ngrok.com/ for exposing the server to a public domain

**Comment by procrastimax** [comment]
Implemented a central server (Option A)
