### ISSUE TITLE
Bug in LoadMore Feature

### ISSUE THREAD

**Issue by yum-yab** [dhelmr/the-holy-search#2]
If you press load more in the UI, it loads the text again and again. The "load more"- button should probably get a load less button if you pressed it once.

**Comment by dhelmr** [comment]
This can be closed, right?

**Comment by procrastimax** [comment]
Yeah, fixed it with: https://github.com/dhelmr/the-holy-search/commit/a5b7ebfe8c05e4372607ec480c9a90f038e000b9
