### ISSUE TITLE
Show if a verse was already classified as relevant or irrelevant

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#25]
It should be shown in the UI if there already exists an entry in the `feedback` table for a document-query pair. If that is the case, maybe highlight the corresponding button. That way different relevancy judgements of the same documents are prevented. 

Also, in the measurement for MAP/NDCG that must be considered, maybe feedback entry is outside the evaluation time range and must be loaded explicitly. But in any case it always must be the newest one, if there are multiple feedback entries for one query-document entry. (**update 07-29:** this part is already implemented)

**Comment by dhelmr** [comment]
for retrieving the feedback in the UI:
```
SELECT * FROM feedback WHERE query = ? AND results_id = ? ORDER BY date DESC LIMIT 1
```
where `query` is the query that is searched for and results_id is the document id for the verse that is retrieved.
please look up the exact column names in `LogDTO`. This query would work for mysql, I'm not sure how the exact syntax for Apache Derby is, especially the DESC and LIMIT parts

If the SQL statement returns an entry, highlight the button in the UI to show that there already was a feedback.

**Comment by yum-yab** [comment]
Does work now, but the LIMIT is no keyword in Apache Derby.
I tried Rownum (like here: http://db.apache.org/derby/faq.html#limit), but didnt work.
If i use `template.apply{
    maxRows = 1
}` its changes the template for all other queries aswell.
I guess i need to generate a seperate Statement for those limited queries, but for now this should work.
