### ISSUE TITLE
Log user interaction

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#4]
This is an official requirement (see https://temir.org/data/lecture-resources/tunit-en-information-retrieval-organization.pdf)

Logs should contain at least:

* user IP
* query
* result click
* dwell time

**Comment by dhelmr** [comment]
I think the logs should be inserted into a new table in Apache Derby (like `ui_logs` or `ui_metrics`). 

Events where a log can be saved:

* user exists page
* user clicks on "show more"/"show less"
* user makes new search query
* (optional) user goes to another tab

maybe you can add an own column "event" and store the event type there as well

**Comment by yum-yab** [comment]
Result Clicks == The verse the user clicked on?

**Comment by dhelmr** [comment]
I think so. Storing the dwell time between for each "Show more" click should already include this.

**Comment by yum-yab** [comment]
Now basic logging is possible, but dwell time & result clicks are still missing

**Comment by dhelmr** [comment]
Please add a table `user_events` where you save:

* event_type (see above)
* User IP 
* Vaadin session id `this.ui.get().session.browser.address`
* timestamp
* time since last event with this session id and user ip (= dwell time)

And a table `result_clicks`:

* user_event_id (references the `user_events` table)
* document id
* textType
* query

**Comment by yum-yab** [comment]
Got the Tables and most of the Logging, but i cant find the vaadin-methods for leaving the page or going to a new tab
